# Generated by Django 5.0.2 on 2024-02-21 17:21
"""
Este módulo de migração alterações.
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """classe de migração de alteração nos modelos Challenge e Work."""

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='page_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='page_nuber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
