# Generated by Django 5.0.2 on 2024-02-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_challenge_page_per_day_work_page_nuber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='page_nuber',
            new_name='page_number',
        ),
    ]
