# Generated by Django 5.0.2 on 2024-03-02 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_work_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='review',
        ),
    ]
