# Generated by Django 5.0.2 on 2024-03-05 17:29
"""
Este módulo de migração do review.
"""

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """classe de migração da alteração de nota da review."""

    dependencies = [
        ('base', '0006_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.FloatField(blank=True, null=True,
                                    validators=[django.core.validators.MinValueValidator(0),
                                                django.core.validators.MaxValueValidator(5)]),
        ),
    ]
