# Generated by Django 5.0.2 on 2024-03-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_review_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='page_per_day',
        ),
        migrations.AddField(
            model_name='work',
            name='genre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
