# Generated by Django 5.0.2 on 2024-04-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_community_communityreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityreview',
            options={},
        ),
        migrations.RemoveField(
            model_name='communityreview',
            name='score',
        ),
        migrations.AddField(
            model_name='communityreview',
            name='like',
            field=models.BooleanField(default=True),
        ),
    ]
